# Workflow to check branch name in PR
# Make sure permissions are set to allow workflow to run
# Go to Settings > Actions > General > Workflow permissions > Allow "Read and write permission" access

name: Branch Check
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Check branch name
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          branch_name=$(echo $GITHUB_HEAD_REF | cut -d '/' -f 2)
          
          if [[ ! $GITHUB_HEAD_REF =~ ^(feature|hotfix)\/[a-zA-Z0-9_-]+-[0-9]+$ ]]; then
            echo "Branch name $GITHUB_HEAD_REF does not match the required format. Please use feature/<feature_name>-<ticket_id> or hotfix/<hotfix_name>-<ticket_id>."
            echo "Closing the pull request..."
            gh pr close $GITHUB_HEAD_REF -c "Branch name $GITHUB_HEAD_REF does not match the required format. Please use feature/<feature_name>-<ticket_id> or hotfix/<hotfix_name>-<ticket_id>."
            exit 1
          fi
          










