# Workflow to check branch name in PR
# Make sure permissions are set to allow workflow to run
# Go to Settings > Actions > General > Workflow permissions > Allow "Read and write permission" access

name: Code Quality Check
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
jobs:
  CodeQualityCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: tsc --noEmit && eslint











